/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property cardContent
 * @property description
 * @property type
 */
@JsonClass(generateAdapter = true)
data class AddonsSetupInstruction(
    @Json(name = "card_content") @field:Json(name = "card_content") var cardContent: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null
)
