/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property instructions
 * @property notification
 */
@JsonClass(generateAdapter = true)
data class AddonsSetupGuide(
    @Json(name = "instructions") @field:Json(name = "instructions") var instructions: List<AddonsSetupInstruction>? = null,
    @Json(name = "notification") @field:Json(name = "notification") var notification: String? = null
)
