/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property createdAt
 * @property description
 * @property eventIcon
 * @property eventStype
 * @property repositoryAvatarIconUrl
 * @property repositoryTitle
 * @property slug
 * @property targetPathString
 * @property title
 */
@JsonClass(generateAdapter = true)
data class V0ActivityEventResponseItemModel(
    @Json(name = "created_at") @field:Json(name = "created_at") var createdAt: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: NullsString? = null,
    @Json(name = "event_icon") @field:Json(name = "event_icon") var eventIcon: NullsString? = null,
    @Json(name = "event_stype") @field:Json(name = "event_stype") var eventStype: NullsString? = null,
    @Json(name = "repository_avatar_icon_url") @field:Json(name = "repository_avatar_icon_url") var repositoryAvatarIconUrl: String? = null,
    @Json(name = "repository_title") @field:Json(name = "repository_title") var repositoryTitle: String? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null,
    @Json(name = "target_path_string") @field:Json(name = "target_path_string") var targetPathString: NullsString? = null,
    @Json(name = "title") @field:Json(name = "title") var title: NullsString? = null
)
