/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property icon
 * @property plan
 * @property planStartedAt
 * @property slug
 * @property title
 */
@JsonClass(generateAdapter = true)
data class V0AddOnAppResponseItemModel(
    @Json(name = "icon") @field:Json(name = "icon") var icon: NullsString? = null,
    @Json(name = "plan") @field:Json(name = "plan") var plan: AddonsPlan? = null,
    @Json(name = "plan_started_at") @field:Json(name = "plan_started_at") var planStartedAt: String? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null
)
