/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property alias
 * @property password
 * @property privateKeyPassword
 * @property uploadFileName
 * @property uploadFileSize
 */
@JsonClass(generateAdapter = true)
data class V0AndroidKeystoreFileUploadParams(
    @Json(name = "alias") @field:Json(name = "alias") var alias: String,
    @Json(name = "password") @field:Json(name = "password") var password: String,
    @Json(name = "private_key_password") @field:Json(name = "private_key_password") var privateKeyPassword: String,
    @Json(name = "upload_file_name") @field:Json(name = "upload_file_name") var uploadFileName: String,
    @Json(name = "upload_file_size") @field:Json(name = "upload_file_size") var uploadFileSize: Int
)
