/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property createdAt
 * @property issuerId
 * @property keyId
 * @property name
 * @property slug
 * @property updatedAt
 */
@JsonClass(generateAdapter = true)
data class V0AppleAPICredentialResponseItem(
    @Json(name = "created_at") @field:Json(name = "created_at") var createdAt: String? = null,
    @Json(name = "issuer_id") @field:Json(name = "issuer_id") var issuerId: String? = null,
    @Json(name = "key_id") @field:Json(name = "key_id") var keyId: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null,
    @Json(name = "updated_at") @field:Json(name = "updated_at") var updatedAt: String? = null
)
