/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property gitOwner The slug of the owner of the repository at the git provider
 * @property gitRepoSlug The slug of the repository at the git provider
 * @property isPublic If &#x60;true&#x60; then the repository visibility setting will be public, in case of &#x60;false&#x60; it will be private
 * @property provider The git provider you are using, it can be &#x60;github&#x60;, &#x60;bitbucket&#x60;, &#x60;gitlab&#x60;, &#x60;gitlab-self-hosted&#x60; or &#x60;custom&#x60;
 * @property repoUrl The URL of your repository
 * @property type It has to be provided by legacy reasons and has to have the &#x60;git&#x60; value
 */
@JsonClass(generateAdapter = true)
data class V0AppUploadParams(
    @Json(name = "git_owner") @field:Json(name = "git_owner") var gitOwner: String,
    @Json(name = "git_repo_slug") @field:Json(name = "git_repo_slug") var gitRepoSlug: String,
    @Json(name = "is_public") @field:Json(name = "is_public") var isPublic: Boolean,
    @Json(name = "provider") @field:Json(name = "provider") var provider: String,
    @Json(name = "repo_url") @field:Json(name = "repo_url") var repoUrl: String,
    @Json(name = "type") @field:Json(name = "type") var type: String
)
