/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property branchName
 * @property buildTriggerToken
 * @property isWebhookAutoRegSupported
 * @property status
 */
@JsonClass(generateAdapter = true)
data class V0AppFinishRespModel(
    @Json(name = "branch_name") @field:Json(name = "branch_name") var branchName: String? = null,
    @Json(name = "build_trigger_token") @field:Json(name = "build_trigger_token") var buildTriggerToken: String? = null,
    @Json(name = "is_webhook_auto_reg_supported") @field:Json(name = "is_webhook_auto_reg_supported") var isWebhookAutoRegSupported: Boolean? = null,
    @Json(name = "status") @field:Json(name = "status") var status: String? = null
)
