/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property artifactMeta
 * @property artifactType
 * @property expiringDownloadUrl
 * @property fileSizeBytes
 * @property isPublicPageEnabled
 * @property publicInstallPageUrl
 * @property slug
 * @property title
 */
@JsonClass(generateAdapter = true)
data class V0ArtifactResponseItemModel(
    @Json(name = "artifact_meta") @field:Json(name = "artifact_meta") var artifactMeta: List<Int>? = null,
    @Json(name = "artifact_type") @field:Json(name = "artifact_type") var artifactType: NullsString? = null,
    @Json(name = "expiring_download_url") @field:Json(name = "expiring_download_url") var expiringDownloadUrl: String? = null,
    @Json(name = "file_size_bytes") @field:Json(name = "file_size_bytes") var fileSizeBytes: Int? = null,
    @Json(name = "is_public_page_enabled") @field:Json(name = "is_public_page_enabled") var isPublicPageEnabled: Boolean? = null,
    @Json(name = "public_install_page_url") @field:Json(name = "public_install_page_url") var publicInstallPageUrl: String? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null,
    @Json(name = "title") @field:Json(name = "title") var title: NullsString? = null
)
