/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property buildNumber
 * @property buildSlug
 * @property buildUrl
 * @property message
 * @property service
 * @property slug
 * @property status
 * @property triggeredWorkflow
 */
@JsonClass(generateAdapter = true)
data class V0BuildTriggerRespModel(
    @Json(name = "build_number") @field:Json(name = "build_number") var buildNumber: Int? = null,
    @Json(name = "build_slug") @field:Json(name = "build_slug") var buildSlug: String? = null,
    @Json(name = "build_url") @field:Json(name = "build_url") var buildUrl: String? = null,
    @Json(name = "message") @field:Json(name = "message") var message: String? = null,
    @Json(name = "service") @field:Json(name = "service") var service: String? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null,
    @Json(name = "status") @field:Json(name = "status") var status: String? = null,
    @Json(name = "triggered_workflow") @field:Json(name = "triggered_workflow") var triggeredWorkflow: String? = null
)
