/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property buildParams The public part of the SSH key you would like to use
 * @property hookInfo
 */
@JsonClass(generateAdapter = true)
data class V0BuildTriggerParams(
    @Json(name = "build_params") @field:Json(name = "build_params") var buildParams: V0BuildTriggerParamsBuildParams? = null,
    @Json(name = "hook_info") @field:Json(name = "hook_info") var hookInfo: V0BuildTriggerParamsHookInfo? = V0BuildTriggerParamsHookInfo()
)
