/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property abortReason
 * @property abortWithSuccess
 * @property skipNotifications
 */
@JsonClass(generateAdapter = true)
data class V0BuildAbortParams(
    @Json(name = "abort_reason") @field:Json(name = "abort_reason") var abortReason: String,
    @Json(name = "abort_with_success") @field:Json(name = "abort_with_success") var abortWithSuccess: Boolean,
    @Json(name = "skip_notifications") @field:Json(name = "skip_notifications") var skipNotifications: Boolean
)
