/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property buildParams
 * @property createdAt
 * @property pullRequestUrl
 * @property slug
 */
@JsonClass(generateAdapter = true)
data class V0BuildRequestResponseItemModel(
    @Json(name = "build_params") @field:Json(name = "build_params") var buildParams: List<Int>? = null,
    @Json(name = "created_at") @field:Json(name = "created_at") var createdAt: String? = null,
    @Json(name = "pull_request_url") @field:Json(name = "pull_request_url") var pullRequestUrl: String? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null
)
