/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property isExpand
 * @property mappedTo
 * @property value
 */
@JsonClass(generateAdapter = true)
data class V0BuildParamsEnvironment(
    @Json(name = "is_expand") @field:Json(name = "is_expand") var isExpand: Boolean? = null,
    @Json(name = "mapped_to") @field:Json(name = "mapped_to") var mappedTo: String? = null,
    @Json(name = "value") @field:Json(name = "value") var value: String? = null
)
