/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property baseRepositoryUrl
 * @property branch
 * @property branchDest
 * @property branchDestRepoOwner
 * @property branchRepoOwner
 * @property buildRequestSlug
 * @property commitHash
 * @property commitMessage
 * @property commitPaths
 * @property diffUrl
 * @property environments
 * @property headRepositoryUrl
 * @property pullRequestAuthor
 * @property pullRequestHeadBranch
 * @property pullRequestId
 * @property pullRequestMergeBranch
 * @property pullRequestRepositoryUrl
 * @property skipGitStatusReport
 * @property tag
 * @property workflowId
 */
@JsonClass(generateAdapter = true)
data class V0BuildTriggerParamsBuildParams(
    @Json(name = "base_repository_url") @field:Json(name = "base_repository_url") var baseRepositoryUrl: String? = null,
    @Json(name = "branch") @field:Json(name = "branch") var branch: String? = null,
    @Json(name = "branch_dest") @field:Json(name = "branch_dest") var branchDest: String? = null,
    @Json(name = "branch_dest_repo_owner") @field:Json(name = "branch_dest_repo_owner") var branchDestRepoOwner: String? = null,
    @Json(name = "branch_repo_owner") @field:Json(name = "branch_repo_owner") var branchRepoOwner: String? = null,
    @Json(name = "build_request_slug") @field:Json(name = "build_request_slug") var buildRequestSlug: String? = null,
    @Json(name = "commit_hash") @field:Json(name = "commit_hash") var commitHash: String? = null,
    @Json(name = "commit_message") @field:Json(name = "commit_message") var commitMessage: String? = null,
    @Json(name = "commit_paths") @field:Json(name = "commit_paths") var commitPaths: List<V0CommitPaths>? = null,
    @Json(name = "diff_url") @field:Json(name = "diff_url") var diffUrl: String? = null,
    @Json(name = "environments") @field:Json(name = "environments") var environments: List<V0BuildParamsEnvironment>? = null,
    @Json(name = "head_repository_url") @field:Json(name = "head_repository_url") var headRepositoryUrl: String? = null,
    @Json(name = "pull_request_author") @field:Json(name = "pull_request_author") var pullRequestAuthor: String? = null,
    @Json(name = "pull_request_head_branch") @field:Json(name = "pull_request_head_branch") var pullRequestHeadBranch: String? = null,
    @Json(name = "pull_request_id") @field:Json(name = "pull_request_id") var pullRequestId: Map<String, Any?>? = null,
    @Json(name = "pull_request_merge_branch") @field:Json(name = "pull_request_merge_branch") var pullRequestMergeBranch: String? = null,
    @Json(name = "pull_request_repository_url") @field:Json(name = "pull_request_repository_url") var pullRequestRepositoryUrl: String? = null,
    @Json(name = "skip_git_status_report") @field:Json(name = "skip_git_status_report") var skipGitStatusReport: Boolean? = null,
    @Json(name = "tag") @field:Json(name = "tag") var tag: String? = null,
    @Json(name = "workflow_id") @field:Json(name = "workflow_id") var workflowId: String? = null
)
