/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property avatarIconUrl
 * @property concurrencyCount
 * @property name
 * @property owners
 * @property slug
 */
@JsonClass(generateAdapter = true)
data class V0OrganizationDataModel(
    @Json(name = "avatar_icon_url") @field:Json(name = "avatar_icon_url") var avatarIconUrl: NullsString? = null,
    @Json(name = "concurrency_count") @field:Json(name = "concurrency_count") var concurrencyCount: Int? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "owners") @field:Json(name = "owners") var owners: List<V0OrganizationOwner>? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null
)
