/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import android.os.Parcelable
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.parcelize.Parcelize

/**
 * @property accountType
 * @property name
 * @property slug
 */
@JsonClass(generateAdapter = true)
@Parcelize
data class V0OwnerAccountResponseModel(
    @Json(name = "account_type") @field:Json(name = "account_type") var accountType: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null
) : Parcelable
