/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property apps
 * @property documentationUrl
 * @property hasUi
 * @property icon
 * @property id
 * @property isBeta
 * @property summary
 * @property title
 */
@JsonClass(generateAdapter = true)
data class V0OwnerAddOnResponseItemModel(
    @Json(name = "apps") @field:Json(name = "apps") var apps: List<V0AddOnAppResponseItemModel>? = null,
    @Json(name = "documentation_url") @field:Json(name = "documentation_url") var documentationUrl: String? = null,
    @Json(name = "has_ui") @field:Json(name = "has_ui") var hasUi: Boolean? = null,
    @Json(name = "icon") @field:Json(name = "icon") var icon: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "is_beta") @field:Json(name = "is_beta") var isBeta: Boolean? = null,
    @Json(name = "summary") @field:Json(name = "summary") var summary: String? = null,
    @Json(name = "title") @field:Json(name = "title") var title: String? = null
)
