/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import android.os.Parcelable
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import kotlinx.parcelize.Parcelize

/**
 * @property next Next is the \&quot;anchor\&quot; for pagination. This value should be passed to the same endpoint to get the next page. Empty/not included if there&#39;s no \&quot;next\&quot; page. Stop paging when there&#39;s no \&quot;Next\&quot; item in the response!
 * @property pageItemLimit PageItemLimit - per-page item count. A given page might include less items if there&#39;s not enough items. This value is the \&quot;max item count per page\&quot;.
 * @property totalItemCount TotalItemCount - total item count, through \&quot;all pages\&quot;
 */
@JsonClass(generateAdapter = true)
@Parcelize
data class V0PagingResponseModel(
    @Json(name = "next") @field:Json(name = "next") var next: String? = null,
    @Json(name = "page_item_limit") @field:Json(name = "page_item_limit") var pageItemLimit: Int? = null,
    @Json(name = "total_item_count") @field:Json(name = "total_item_count") var totalItemCount: Int? = null
) : Parcelable
