/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property downloadUrl
 * @property exposedMetaDatastore
 * @property isExpose
 * @property isProtected
 * @property processed
 * @property slug
 * @property uploadFileName
 * @property uploadFileSize
 * @property uploadUrl
 * @property userEnvKey
 */
@JsonClass(generateAdapter = true)
data class V0ProjectFileStorageResponseItemModel(
    @Json(name = "download_url") @field:Json(name = "download_url") var downloadUrl: String? = null,
    @Json(name = "exposed_meta_datastore") @field:Json(name = "exposed_meta_datastore") var exposedMetaDatastore: List<Int>? = null,
    @Json(name = "is_expose") @field:Json(name = "is_expose") var isExpose: Boolean? = null,
    @Json(name = "is_protected") @field:Json(name = "is_protected") var isProtected: Boolean? = null,
    @Json(name = "processed") @field:Json(name = "processed") var processed: Boolean? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null,
    @Json(name = "upload_file_name") @field:Json(name = "upload_file_name") var uploadFileName: String? = null,
    @Json(name = "upload_file_size") @field:Json(name = "upload_file_size") var uploadFileSize: Int? = null,
    @Json(name = "upload_url") @field:Json(name = "upload_url") var uploadUrl: String? = null,
    @Json(name = "user_env_key") @field:Json(name = "user_env_key") var userEnvKey: String? = null
)
