/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property uploadFileName
 * @property uploadFileSize
 * @property userEnvKey
 */
@JsonClass(generateAdapter = true)
data class V0ProjectFileStorageUploadParams(
    @Json(name = "upload_file_name") @field:Json(name = "upload_file_name") var uploadFileName: String,
    @Json(name = "upload_file_size") @field:Json(name = "upload_file_size") var uploadFileSize: Int,
    @Json(name = "user_env_key") @field:Json(name = "user_env_key") var userEnvKey: String
)
