/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property errorMsg
 */
@JsonClass(generateAdapter = true)
data class V0ProxyErrorRespModel(
    @Json(name = "error_msg") @field:Json(name = "error_msg") var errorMsg: String? = null
)
