/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property authSshPrivateKey The private part of the SSH key you would like to use
 * @property authSshPublicKey The public part of the SSH key you would like to use
 * @property isRegisterKeyIntoProviderService If it&#39;s set to true, the provided SSH key will be registered at the provider of the application
 */
@JsonClass(generateAdapter = true)
data class V0SSHKeyUploadParams(
    @Json(name = "auth_ssh_private_key") @field:Json(name = "auth_ssh_private_key") var authSshPrivateKey: String,
    @Json(name = "auth_ssh_public_key") @field:Json(name = "auth_ssh_public_key") var authSshPublicKey: String,
    @Json(name = "is_register_key_into_provider_service") @field:Json(name = "is_register_key_into_provider_service") var isRegisterKeyIntoProviderService: Boolean? = null
)
