/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property deviceId
 * @property deviceType
 * @property owner
 */
@JsonClass(generateAdapter = true)
data class V0TestDeviceResponseItemModel(
    @Json(name = "device_id") @field:Json(name = "device_id") var deviceId: String? = null,
    @Json(name = "device_type") @field:Json(name = "device_type") var deviceType: String? = null,
    @Json(name = "owner") @field:Json(name = "owner") var owner: String? = null
)
