/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import za.co.app.bitrisebuddy.model.data.models.V0PlanDataModel

/**
 * @property currentPlan
 * @property pendingPlan
 * @property trialExpiresAt
 */
@JsonClass(generateAdapter = true)
data class V0UserPlanDataModel(
    @Json(name = "current_plan") @field:Json(name = "current_plan") var currentPlan: V0PlanDataModel? = null,
    @Json(name = "pending_plan") @field:Json(name = "pending_plan") var pendingPlan: V0PlanDataModel? = null,
    @Json(name = "trial_expires_at") @field:Json(name = "trial_expires_at") var trialExpiresAt: String? = null
)
