/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property avatarUrl
 * @property createdAt
 * @property dataId
 * @property email
 * @property hasUsedOrganizationTrial
 * @property paymentProcessor
 * @property slug
 * @property unconfirmedEmail
 * @property username
 */
@JsonClass(generateAdapter = true)
data class V0UserProfileDataModel(
    @Json(name = "avatar_url") @field:Json(name = "avatar_url") var avatarUrl: String? = null,
    @Json(name = "created_at") @field:Json(name = "created_at") var createdAt: String? = null,
    @Json(name = "data_id") @field:Json(name = "data_id") var dataId: Int? = null,
    @Json(name = "email") @field:Json(name = "email") var email: String? = null,
    @Json(name = "has_used_organization_trial") @field:Json(name = "has_used_organization_trial") var hasUsedOrganizationTrial: Boolean? = null,
    @Json(name = "payment_processor") @field:Json(name = "payment_processor") var paymentProcessor: String? = null,
    @Json(name = "slug") @field:Json(name = "slug") var slug: String? = null,
    @Json(name = "unconfirmed_email") @field:Json(name = "unconfirmed_email") var unconfirmedEmail: String? = null,
    @Json(name = "username") @field:Json(name = "username") var username: String? = null
)
