/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.apis

import retrofit2.http.GET
import retrofit2.http.Headers
import za.co.app.bitrisebuddy.model.data.models.V0AddonsListResponseModel
import za.co.app.bitrisebuddy.model.data.models.V0AddonsShowResponseModel
import za.co.app.bitrisebuddy.model.data.models.V0AppAddOnsListResponseModel
import za.co.app.bitrisebuddy.model.data.models.V0OwnerAddOnsListResponseModel

@JvmSuppressWildcards
interface AddonsApi {
    /**
     * Get list of the addons for apps
     * List all the provisioned addons for the authorized apps
     * The endpoint is owned by defaultname service owner
     * @param appSlug App slug (required)
     */
    @Headers(
        "X-Operation-ID: addon-list-by-app"
    )
    @GET("apps/{app-slug}/addons")
    suspend fun addonListByApp(
        @retrofit2.http.Path("app-slug") appSlug: String
    ): V0AppAddOnsListResponseModel
    /**
     * Get list of the addons for organization
     * List all the provisioned addons for organization
     * The endpoint is owned by defaultname service owner
     * @param organizationSlug Organization slug (required)
     */
    @Headers(
        "X-Operation-ID: addon-list-by-organization"
    )
    @GET("organizations/{organization-slug}/addons")
    suspend fun addonListByOrganization(
        @retrofit2.http.Path("organization-slug") organizationSlug: String
    ): V0OwnerAddOnsListResponseModel
    /**
     * Get list of the addons for user
     * List all the provisioned addons for the authenticated user
     * The endpoint is owned by defaultname service owner
     * @param userSlug User slug (required)
     */
    @Headers(
        "X-Operation-ID: addon-list-by-user"
    )
    @GET("users/{user-slug}/addons")
    suspend fun addonListByUser(
        @retrofit2.http.Path("user-slug") userSlug: String
    ): V0OwnerAddOnsListResponseModel
    /**
     * Get list of available Bitrise addons
     * List all the available Bitrise addons
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: addons-list"
    )
    @GET("addons")
    suspend fun addonsList(): V0AddonsListResponseModel
    /**
     * Get a specific Bitrise addon
     * Show details of a specific Bitrise addon
     * The endpoint is owned by defaultname service owner
     * @param addonId Addon ID (required)
     */
    @Headers(
        "X-Operation-ID: addons-show"
    )
    @GET("addons/{addon-id}")
    suspend fun addonsShow(
        @retrofit2.http.Path("addon-id") addonId: String
    ): V0AddonsShowResponseModel
}
