/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.apis

import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST
import za.co.app.bitrisebuddy.model.data.models.V0AndroidKeystoreFileUploadParams
import za.co.app.bitrisebuddy.model.data.models.V0ProjectFileStorageListResponseModel
import za.co.app.bitrisebuddy.model.data.models.V0ProjectFileStorageResponseModel

@JvmSuppressWildcards
interface AndroidKeystoreFileApi {
    /**
     * Create an Android keystore file
     * Add a new Android keystore file to an app
     * The endpoint is owned by defaultname service owner
     * @param appSlug App slug (required)
     * @param androidKeystoreFile Android keystore file parameters (required)
     */
    @Headers(
        "X-Operation-ID: android-keystore-file-create",
      "Content-Type: application/json"
    )
    @POST("apps/{app-slug}/android-keystore-files")
    suspend fun androidKeystoreFileCreate(
        @retrofit2.http.Path("app-slug") appSlug: String,
        @retrofit2.http.Body androidKeystoreFile: V0AndroidKeystoreFileUploadParams
    ): V0ProjectFileStorageResponseModel
    /**
     * Get a list of the android keystore files
     * List all the android keystore files that have been uploaded to a specific app.
     * The endpoint is owned by defaultname service owner
     * @param appSlug App slug (required)
     * @param next Slug of the first android keystore file in the response (optional)
     * @param limit Max number of build certificates per page is 50. (optional)
     */
    @Headers(
        "X-Operation-ID: android-keystore-file-list"
    )
    @GET("apps/{app-slug}/android-keystore-files")
    suspend fun androidKeystoreFileList(
        @retrofit2.http.Path("app-slug") appSlug: String,
        @retrofit2.http.Query("next") next: String?,
        @retrofit2.http.Query("limit") limit: Int?
    ): V0ProjectFileStorageListResponseModel
}
