/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.apis

import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.PATCH
import retrofit2.http.POST
import za.co.app.bitrisebuddy.model.data.models.V0AvatarCandidateCreateParams
import za.co.app.bitrisebuddy.model.data.models.V0AvatarCandidateCreateResponseItem
import za.co.app.bitrisebuddy.model.data.models.V0AvatarPromoteParams
import za.co.app.bitrisebuddy.model.data.models.V0AvatarPromoteResponseModel
import za.co.app.bitrisebuddy.model.data.models.V0FindAvatarCandidateResponse

@JvmSuppressWildcards
interface AvatarCandidateApi {
    /**
     * Create avatar candidates
     * Add new avatar candidates to a specific app
     * The endpoint is owned by defaultname service owner
     * @param appSlug App slug (required)
     * @param avatarCandidate Avatar candidate parameters (required)
     */
    @Headers(
        "X-Operation-ID: avatar-candidate-create",
      "Content-Type: application/json"
    )
    @POST("apps/{app-slug}/avatar-candidates")
    suspend fun avatarCandidateCreate(
        @retrofit2.http.Path("app-slug") appSlug: String,
        @retrofit2.http.Body avatarCandidate: List<V0AvatarCandidateCreateParams>
    ): List<V0AvatarCandidateCreateResponseItem>
    /**
     * Get list of the avatar candidates
     * List all available avatar candidates for an application
     * The endpoint is owned by defaultname service owner
     * @param appSlug App slug (required)
     */
    @Headers(
        "X-Operation-ID: avatar-candidate-list",
      "Content-Type: application/json"
    )
    @GET("v0.1/apps/{app-slug}/avatar-candidates")
    suspend fun avatarCandidateList(
        @retrofit2.http.Path("app-slug") appSlug: String
    ): V0FindAvatarCandidateResponse
    /**
     * Promote an avatar candidate
     * Promotes an avatar candidate for an app
     * The endpoint is owned by defaultname service owner
     * @param appSlug App slug (required)
     * @param avatarSlug Avatar candidate slug (required)
     * @param avatarPromoteParams Avatar promote parameters (required)
     */
    @Headers(
        "X-Operation-ID: avatar-candidate-promote",
      "Content-Type: application/json"
    )
    @PATCH("apps/{app-slug}/avatar-candidates/{avatar-slug}")
    suspend fun avatarCandidatePromote(
        @retrofit2.http.Path("app-slug") appSlug: String,
        @retrofit2.http.Path("avatar-slug") avatarSlug: String,
        @retrofit2.http.Body avatarPromoteParams: V0AvatarPromoteParams
    ): V0AvatarPromoteResponseModel
}
