/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.apis

import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.PATCH
import za.co.app.bitrisebuddy.model.data.models.V0BuildRequestListResponseModel
import za.co.app.bitrisebuddy.model.data.models.V0BuildRequestUpdateParams
import za.co.app.bitrisebuddy.model.data.models.V0BuildRequestUpdateResponseModel

@JvmSuppressWildcards
interface BuildRequestApi {
    /**
     * List the open build requests for an app
     * List the existing open build requests of a specified Bitrise app
     * The endpoint is owned by defaultname service owner
     * @param appSlug App slug (required)
     */
    @Headers(
        "X-Operation-ID: build-request-list"
    )
    @GET("apps/{app-slug}/build-requests")
    suspend fun buildRequestList(
        @retrofit2.http.Path("app-slug") appSlug: String
    ): V0BuildRequestListResponseModel
    /**
     * Update a build request
     * Update a specific build request of a specific app
     * The endpoint is owned by defaultname service owner
     * @param appSlug App slug (required)
     * @param buildRequestSlug Build request slug (required)
     * @param buildRequest Build request parameters (required)
     */
    @Headers(
        "X-Operation-ID: build-request-update",
      "Content-Type: application/json"
    )
    @PATCH("apps/{app-slug}/build-requests/{build-request-slug}")
    suspend fun buildRequestUpdate(
        @retrofit2.http.Path("app-slug") appSlug: String,
        @retrofit2.http.Path("build-request-slug") buildRequestSlug: String,
        @retrofit2.http.Body buildRequest: V0BuildRequestUpdateParams
    ): V0BuildRequestUpdateResponseModel
}
