/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.apis

import retrofit2.http.GET
import retrofit2.http.Headers
import za.co.app.bitrisebuddy.model.data.models.V0OrganizationListRespModel
import za.co.app.bitrisebuddy.model.data.models.V0OrganizationRespModel

@JvmSuppressWildcards
interface OrganizationsApi {
    /**
     * List the organizations that the user is part of
     * List all Bitrise organizations that the user is part of
     * The endpoint is owned by defaultname service owner
     */
    @Headers(
        "X-Operation-ID: org-list"
    )
    @GET("organizations")
    suspend fun orgList(): V0OrganizationListRespModel
    /**
     * Get a specified organization.
     * Get a specified Bitrise organization that the user is part of.
     * The endpoint is owned by defaultname service owner
     * @param orgSlug The organization slug (required)
     */
    @Headers(
        "X-Operation-ID: org-show"
    )
    @GET("organizations/{org-slug}")
    suspend fun orgShow(
        @retrofit2.http.Path("org-slug") orgSlug: String
    ): V0OrganizationRespModel
}
