/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Bitrise API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package za.co.app.bitrisebuddy.model.data.apis

import retrofit2.http.GET
import retrofit2.http.Headers
import za.co.app.bitrisebuddy.model.data.models.V0TestDeviceListResponseModel

@JvmSuppressWildcards
interface TestDevicesApi {
    /**
     * List the test devices for an app
     * List registered test devices of all members of a specified Bitrise app
     * The endpoint is owned by defaultname service owner
     * @param appSlug App slug (required)
     */
    @Headers(
        "X-Operation-ID: test-device-list"
    )
    @GET("apps/{app-slug}/test-devices")
    suspend fun testDeviceList(
        @retrofit2.http.Path("app-slug") appSlug: String
    ): V0TestDeviceListResponseModel
}
